### ISSUE TITLE
Auto scroll from assembly results in "Cursor position outside buffer"

### ISSUE THREAD

**Issue by Fabian-programmer** [krady21/compiler-explorer.nvim#10]
> 
Error executing lua callback: ...compiler-explorer.nvim/lua/compiler-explorer/autocmd.lua:87: Cursor position outside buffer

Example:
```
#include <iostream>

using namespace std;

int main(int argc, char **argv) {

  cout << "You have entered " << argc << " arguments:"
       << "\n";

  for (int i = 0; i < argc; ++i)
    cout << argv[i] << "\n";

  while (1 == 1) {
    cout << "yes" << endl;
  }
}
```

Compilled with gcc 11.3 -O0.

![grafik](https://user-images.githubusercontent.com/65787013/209466524-efa857de-dcde-4e99-8670-636405c0b216.png)

Compiling with -O3 results in even more of these errors.

**Comment by krady21** [comment]
Hi. I've noticed this behavior before but I did not have the time to investigate. It seems that the problem comes from what the godbolt REST API sends back in the asm field when making an `/api/compiler/g113/compile` POST request. Some of the entries in the asm field that are used for line highlighting/jumping are lines that are outside the source buffer (eg: 616, 880). This means that we are either not setting a necessary config option in the compile body or there is a problem with the REST API itself. In the latter case,  we should probably open an issue [upstream](https://github.com/compiler-explorer/compiler-explorer). Either way, I think that wrapping the `api.nvim_win_set_cursor()` with a pcall might fix this temporarily until we find out what botches the REST API response.

**Comment by krady21** [comment]
The lines that are outside the buffer seem to be corresponding to library header files. Check lines 67 or 68 from the REST API response using dev tools here: https://godbolt.org/z/6nvch3aPh . I'll make sure to filter them before adding them to the highlights table.

**Comment by krady21** [comment]
This should be fixed. Feel free to reopen this if it still happens.

**Comment by Fabian-programmer** [comment]
Thanks for the insights.

I don't think it fixed the bug, because the underlying problem is that the highlighter uses line number from other files than the buffer.
When the imported file has a line number which is smaller than the current buffers line number, it is going to highlight false lines.

**Comment by Fabian-programmer** [comment]
Feel free to cherry-pick it
https://github.com/krady21/compiler-explorer.nvim/commit/0787a64b0133057dcc67f32c73eb93cba044d591
